/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardQuotesRouteImport } from './routes/_dashboard.quotes'
import { Route as DashboardContactRequestsRouteImport } from './routes/_dashboard.contact-requests'
import { Route as DashboardContactInfoRouteImport } from './routes/_dashboard.contact-info'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuotesRoute = DashboardQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContactRequestsRoute =
  DashboardContactRequestsRouteImport.update({
    id: '/contact-requests',
    path: '/contact-requests',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardContactInfoRoute = DashboardContactInfoRouteImport.update({
  id: '/contact-info',
  path: '/contact-info',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/contact-info': typeof DashboardContactInfoRoute
  '/contact-requests': typeof DashboardContactRequestsRoute
  '/quotes': typeof DashboardQuotesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/contact-info': typeof DashboardContactInfoRoute
  '/contact-requests': typeof DashboardContactRequestsRoute
  '/quotes': typeof DashboardQuotesRoute
  '/': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/contact-info': typeof DashboardContactInfoRoute
  '/_dashboard/contact-requests': typeof DashboardContactRequestsRoute
  '/_dashboard/quotes': typeof DashboardQuotesRoute
  '/_dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/contact-info' | '/contact-requests' | '/quotes'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/contact-info' | '/contact-requests' | '/quotes' | '/'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/contact-info'
    | '/_dashboard/contact-requests'
    | '/_dashboard/quotes'
    | '/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/quotes': {
      id: '/_dashboard/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof DashboardQuotesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/contact-requests': {
      id: '/_dashboard/contact-requests'
      path: '/contact-requests'
      fullPath: '/contact-requests'
      preLoaderRoute: typeof DashboardContactRequestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/contact-info': {
      id: '/_dashboard/contact-info'
      path: '/contact-info'
      fullPath: '/contact-info'
      preLoaderRoute: typeof DashboardContactInfoRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardContactInfoRoute: typeof DashboardContactInfoRoute
  DashboardContactRequestsRoute: typeof DashboardContactRequestsRoute
  DashboardQuotesRoute: typeof DashboardQuotesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardContactInfoRoute: DashboardContactInfoRoute,
  DashboardContactRequestsRoute: DashboardContactRequestsRoute,
  DashboardQuotesRoute: DashboardQuotesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
